\subsection{Variables}
\verb|$@|: target name\\
\verb|$^|: first prerequisite\\
\verb|$$X|: Access to the user var. X\\

\subsection{Syntax}
\begin{verbatim}
target: prerequisite1 prerequisite2 ...
  commands
\end{verbatim}
